"""a few more changes to the tables

Revision ID: 1fec25e79abc
Revises: 475a93ef4fcc
Create Date: 2023-05-18 15:54:35.908831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fec25e79abc'
down_revision = '475a93ef4fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('phrase1', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('phrase2', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('phrase3', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('phrase4', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('phrase5', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('phrase6', sa.String(), nullable=True))
    op.drop_column('characters', 'dialogue1')
    op.drop_column('characters', 'dialogue2')
    op.drop_column('characters', 'dialogue4')
    op.drop_column('characters', 'alive')
    op.drop_column('characters', 'dialogue3')
    op.drop_column('characters', 'dialogue5')
    op.drop_column('characters', 'completed')
    op.add_column('items', sa.Column('use', sa.String(), nullable=True))
    op.add_column('items', sa.Column('correct_room_id', sa.Integer(), nullable=True))
    op.drop_column('items', 'taken')
    op.drop_column('players', 'dead')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('dead', sa.BOOLEAN(), nullable=True))
    op.add_column('items', sa.Column('taken', sa.BOOLEAN(), nullable=True))
    op.drop_column('items', 'correct_room_id')
    op.drop_column('items', 'use')
    op.add_column('characters', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    op.add_column('characters', sa.Column('dialogue5', sa.VARCHAR(), nullable=True))
    op.add_column('characters', sa.Column('dialogue3', sa.VARCHAR(), nullable=True))
    op.add_column('characters', sa.Column('alive', sa.BOOLEAN(), nullable=True))
    op.add_column('characters', sa.Column('dialogue4', sa.VARCHAR(), nullable=True))
    op.add_column('characters', sa.Column('dialogue2', sa.VARCHAR(), nullable=True))
    op.add_column('characters', sa.Column('dialogue1', sa.VARCHAR(), nullable=True))
    op.drop_column('characters', 'phrase6')
    op.drop_column('characters', 'phrase5')
    op.drop_column('characters', 'phrase4')
    op.drop_column('characters', 'phrase3')
    op.drop_column('characters', 'phrase2')
    op.drop_column('characters', 'phrase1')
    # ### end Alembic commands ###
