"""added taken column to item table

Revision ID: 251b2a6d327b
Revises: f13f8ad416ef
Create Date: 2023-05-17 23:38:42.841100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251b2a6d327b'
down_revision = 'f13f8ad416ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dialogue1', sa.String(), nullable=True),
    sa.Column('dialogue2', sa.String(), nullable=True),
    sa.Column('dialogue3', sa.String(), nullable=True),
    sa.Column('dialogue4', sa.String(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_npcs_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('taken', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'taken')
    op.drop_table('npcs')
    # ### end Alembic commands ###
