"""create player and location model

Revision ID: e2519d773ab4
Revises: 
Create Date: 2023-05-16 19:06:48.131842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2519d773ab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('look', sa.String(), nullable=True),
    sa.Column('up', sa.String(), nullable=True),
    sa.Column('down', sa.String(), nullable=True),
    sa.Column('left', sa.String(), nullable=True),
    sa.Column('right', sa.String(), nullable=True),
    sa.Column('outside', sa.String(), nullable=True),
    sa.Column('inside', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('dead', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('locations')
    # ### end Alembic commands ###
