"""modified npc table

Revision ID: e837c481cf60
Revises: 251b2a6d327b
Create Date: 2023-05-18 11:43:46.132265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e837c481cf60'
down_revision = '251b2a6d327b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'completed')
    # ### end Alembic commands ###
